### ISSUE TITLE
Documentation Boo-boos

### ISSUE THREAD

**Issue by ong-yinggao98** [AY2021S1-CS2103T-W15-2/tp#248]
3.4 of UG - need to remove unnecessary capitalisation
3.6 of TOC - broken links
1.2 of UG table - inconsistent formatting
3.2.3 - description sounds gay

Design considerations (Questions) DG - need table of content
Manual testing - need table of content

**Comment by AlexCQY** [comment]
User guide toc "2.2 Making sense of Reeve’s layout"  does not work

**Comment by AlexCQY** [comment]
User guide toc "3.3.9 Viewing lesson schedule: schedule (By: Alex Chua)" does not work

**Comment by AlexCQY** [comment]
User guide toc notes subsection does not work
![Uploading image.png…]()

**Comment by AlexCQY** [comment]
Incorrect format in "4.Command Summary"
![image](https://user-images.githubusercontent.com/59348559/98466679-06903c80-220c-11eb-996c-18f6d60eb8dd.png)

**Comment by AlexCQY** [comment]
Reeve should be bolded here
![image](https://user-images.githubusercontent.com/59348559/98466708-42c39d00-220c-11eb-8cfc-ad6d7b3a2f15.png)

**Comment by hogantan** [comment]
Summary of symbols (Table 1) --> capitalize first letter

Numbering of figures

(Add command) Can rearrange add command bullet points to match arrangement of format

(Add command) Repeat of Format twice

(Schedule) Exclamation symbol 

(Clear command) Can be more user centric

(Exam Add Command) Missing grey highlights for ALL CAPS words

(Attendance Add Command) Missing grey highlights for ALL CAPS words

(Notebook feature 3.6) CAPS all first letter

**Comment by AlexCQY** [comment]
May this can state it is about the class time or can indicate as a warning?
![image](https://user-images.githubusercontent.com/59348559/98467191-034a8000-220f-11eb-993c-156e8a758614.png)

**Comment by hogantan** [comment]
Summary of symbols (Table 1) --> can remove ... indicates --> just go straight to the point


Summary of symbols (Table 1) --> what does grey highlight actually mean? --> since we use it for methods/classes and all


Update TOC to include the updated manual testing 

Last line |||||| master

Duplicate Logic class diagram (before 5.3 and after)

Remove bolded term definition for blue boxes

Labelling of diagrams and Update old figure numbers

6.1.3 point 3, weird phrasing? --> reeve is then exited

6.3.2.1 point 6 is change to has, of change to as 

6.3.2.1 last sentence --> similar to add attendance (rather than question) 

6.3.2.2 last sentence --> similar to delete attendance (rather than question) 

6.4 Blue box for information 

Combine Design Considerations sections into feature sectiosn (see 6.1.2)

Arrange manuael testing section

Numbering of use cases
